### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by yufengya0420** [Tsubasa6848/Cleaner#7]
11:12:03 ERROR [LiteLoader] SEH exception occurred in ScheduleTask! 
11:12:03 ERROR [LiteLoader] SEH_UNKNOW_ERROR 
11:12:03 ERROR [LiteLoader] TaskId: 526 
11:12:03 ERROR [LiteLoader] In Plugin: <Cleaner 1.6.51>

**Comment by Tsubasa6848** [comment]
光从这个得不到任何信息，请提供复现方法
